name: flad_cli
description: Flutter UI component copier CLI for Flutter projects.
version: 0.0.3
repository: https://github.com/Shohjahon-n/flad
homepage: https://github.com/Shohjahon-n/flad

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  args: ^2.5.0
  path: ^1.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8

executables:
  flad: flad_cli
